### ISSUE TITLE
Is there any example that I can refer to? Can I automatically access the yii2 framework with zero code?

### ISSUE THREAD

**Issue by runtu666** [opentelemetry-php/contrib-auto-yii#1]
Is there any example that I can refer to? Can I automatically access the yii2 framework with zero code?

**Comment by buildyuan** [comment]
maybe see this 

https://github.com/opentelemetry-php/example-auto-yii

**Comment by brettmc** [comment]
Sorry, didn't see this issue because this is a read-only clone from upstream. Closing, because I think you've also raised this upstream and made progress.
