### ISSUE TITLE
Getting unknown property: yii\web\ErrorAction::actionMethod

### ISSUE THREAD

**Issue by buildyuan** [opentelemetry-php/contrib-auto-yii#3]
I tried this demo, 
it not work you visit some  actions Method, such as 
```php
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
```
he said : 
```
Unknown Property – [yii\base\UnknownPropertyException](https://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Getting unknown property: yii\web\ErrorAction::actionMethod
```

but it work very good when you visit some Method like `actionIndex`

```php
   /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
```

**Comment by buildyuan** [comment]
Only the `yii\base\InlineAction` class possesses the `actionMethod` property.
What can I  do if a method inherited from `yii\base\Action`?
it does not have this property `actionMethod` ?

**Comment by brettmc** [comment]
> I tried this demo

Do you mean https://github.com/opentelemetry-php/example-auto-yii ? If so, this sounds like a problem with the `yiisoft/yii2-app-basic` project that the demo runs off. If you disable opentelemetry (set `OTEL_PHP_AUTOLOAD_ENABLED=false` in `docker-compose.yaml`) and the it is still broken, does it still not work?

**Comment by brettmc** [comment]
@buildyuan this repository is a read-only mirror of our primary repository. Please raise this over in https://github.com/open-telemetry/opentelemetry-php/issues - I'm going to close this issue and in a couple of days I'll disable issues here, because this is not a supported/monitored issue tracker (sorry!).
